# scipy special functions

scipy.special.jn()
scipy.special.ellipj()
scipy.special.gamma()
scipy.special.gammaln()
scipy.special.erf()

In [1]:
from scipy import linalg
import numpy as np

In [2]:
arr = np.array([[1,2],[3,4]])

linalg.det(arr)

#1*4-2*3 = 4-6 = -2

-2.0


In [3]:
linalg.det(np.ones((1,2)))

ValueError: expected square matrix

In [4]:
linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
linalg.inv(np.ones((1,2)))

ValueError: expected square matrix

In [6]:
linalg.svd(arr)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

scipy.interpolate